version: '3.3'
services:
  dev-db:
    platform: linux/x86_64
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - dev-db:/var/lib/mysql
  test-db:
    platform: linux/x86_64
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_DATABASE: 'test_db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - test-db:/var/lib/mysql
volumes:
  dev-db:
  test-db:
